#Advance_Python
#Exception Handling
#zero division pgm

num1=int(input("enter num1"))  #1
num2=int(input("enter num2"))   #0
try:
    res=num1/num2
    print(res)
except:
    print("exception occured")

